### ISSUE TITLE
Table of Contents is Duplicated

### ISSUE THREAD

**Issue by mathisonryan** [DBOMproject/database-agent#203]
**URL(s) with the issue:**

[Please provide a link to the documentation entry](https://github.com/DBOMproject/database-agent/blob/2.0.0-alpha-1/README.md)

**Description of the issue:**

Table of Contents is Duplicated

**Submitting a pull request?**

Are you willing to submit a pull request to solve this issue? (Yes/No): Yes

**Comment by NnajiChimuanya** [comment]
Yes

**Comment by NnajiChimuanya** [comment]
Assign it to me

**Comment by irajeshegde** [comment]
@NnajiChimuanya - please raise a PR to `2.0.0-alpha-1` branch once updated. Thanks!

**Comment by irajeshegde** [comment]
This is now updated in [commit](https://github.com/DBOMproject/database-agent/commit/44c728677103f48ec622c05298ac42f09eaa88b1). Hence closing this issue.
